### ISSUE TITLE
Thank you! migrated from cloudwatch-adapter to keda

### ISSUE THREAD

**Issue by afirth** [Pluies/external-metrics-multiplexer#2]
hi Florent,

just wanted to thank you for taking the time and effort to publish this. Invaluable in our smooth migration from cloudwatch-adapter to keda. Leaving this here in case any future googlers come past

snippet: values.yaml
```yaml
# URL of the default metrics provider which provides the base path, for example:
#
# defaultProviderUrl: prometheus-adapter.prometheus.svc.cluster.local
defaultProviderUrl: k8s-cloudwatch-adapter.custom-metrics.svc.cluster.local

# A list of the metrics providers you want to support, for example:
#
metricsProviders:
- name: keda
  prefix: "s\\d" #s0-my-service-scaler-metric #note the first \ is for yaml
  strip_prefix: false
  service: keda-operator-metrics-apiserver.keda.svc.cluster.local
```
